import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Script from "next/script";

export const metadata = {
  title: "Aj Auction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

        {/* Font Awesome (CDN) */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />

        {/* Site Styles (from public folder) */}
        <link rel="stylesheet" href="/fonts/stylesheet.css" />
        <link rel="stylesheet" href="/css/animation.css" />
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/css/slick.css" />

        {/* Optional: Font Awesome Pro (if you're using this specifically) */}
        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.2/css/all.css"
        />
      </head>
      <body>
        <Header />
        {children}
        <Footer />

        {/* JS Scripts */}
        <Script src="https://code.jquery.com/jquery-3.7.1.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-auto-scroll@0.5.3/dist/js/splide-extension-auto-scroll.min.js" />
        <Script src="/js/common.js" />
      </body>
    </html>
  );
}


// import Footer from "@/components/Footer";
// import Header from "@/components/Header";
// import Script from "next/script";

// export const metadata = {
//   title: "Aj Acution",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>


//             {/* <!-- fabicon --> */}
//     <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"></link>
//         {/* Font Awesome */}
      
//     <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"></link>
//     <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css"></link>
//     <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css"></link>
//     <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/regular.min.css"></link>
//     <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css"></link>
    

//         {/* Local Styles */}
//       <link href="https://site-assets.fontawesome.com/releases/v6.5.2/css/all.css" ></link>
//     <link href="fonts/stylesheet.css"  type="text/css"></link>
//     <link href="css/animation.css"  type="text/css"></link>
//     <link href="css/bootstrap.min.css"  type="text/css"></link>
//     <link href="css/style.css"  type="text/css"></link>
//     <link href="css/slick.css"  type="text/css"></link>
    
    
//       </head>
//       <body>
        
//         <Header />
//           {children}
//         <Footer/>

//        <Script src="https://code.jquery.com/jquery-3.7.1.min.js" ></Script>
//    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></Script>
//    <Script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></Script>
//    <Script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" ></Script>
//    <Script src="
//         https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-auto-scroll@0.5.3/dist/js/splide-extension-auto-scroll.min.js
//         "></Script>
//    <Script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></Script>


//        <Script src="/js/common.js"></Script>
//       </body>
//     </html>
//   );
// }
